version: '3'
services:
  
  postgres:
    image: postgres:latest
    ports:
      - '4321:5432'
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

    volumes:
      - ./postgres-db:/var/lib/postgresql/data
  
  
  server:
    build: .
    depends_on:
      - postgres

    ports:
      - "3000:3000"

volumes:
  postgres-db: