version: "3.8"
services:
  terminal-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDOAR_USEPOLLING=true

    # env_file:
    # -./.env
  
    